// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdminAddMember(arg1, arg2) {
  return window['go']['main']['App']['AdminAddMember'](arg1, arg2);
}

export function AdminArchiveGroup(arg1, arg2) {
  return window['go']['main']['App']['AdminArchiveGroup'](arg1, arg2);
}

export function AdminCreateGroup(arg1) {
  return window['go']['main']['App']['AdminCreateGroup'](arg1);
}

export function AdminCreateUser(arg1, arg2, arg3) {
  return window['go']['main']['App']['AdminCreateUser'](arg1, arg2, arg3);
}

export function AdminListDevices() {
  return window['go']['main']['App']['AdminListDevices']();
}

export function AdminListGroups() {
  return window['go']['main']['App']['AdminListGroups']();
}

export function AdminListMembers(arg1) {
  return window['go']['main']['App']['AdminListMembers'](arg1);
}

export function AdminListUsers() {
  return window['go']['main']['App']['AdminListUsers']();
}

export function AdminRemoveMember(arg1, arg2, arg3) {
  return window['go']['main']['App']['AdminRemoveMember'](arg1, arg2, arg3);
}

export function AdminUnarchiveGroup(arg1) {
  return window['go']['main']['App']['AdminUnarchiveGroup'](arg1);
}

export function AutoUnlockEnabled() {
  return window['go']['main']['App']['AutoUnlockEnabled']();
}

export function Bootstrap(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Bootstrap'](arg1, arg2, arg3, arg4, arg5);
}

export function DataDir() {
  return window['go']['main']['App']['DataDir']();
}

export function DeleteEntry(arg1) {
  return window['go']['main']['App']['DeleteEntry'](arg1);
}

export function DisableAutoUnlock() {
  return window['go']['main']['App']['DisableAutoUnlock']();
}

export function EnableAutoUnlock() {
  return window['go']['main']['App']['EnableAutoUnlock']();
}

export function ExportKeyfile(arg1) {
  return window['go']['main']['App']['ExportKeyfile'](arg1);
}

export function GenerateKeypair(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateKeypair'](arg1, arg2, arg3);
}

export function GeneratePassword(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GeneratePassword'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetCA() {
  return window['go']['main']['App']['GetCA']();
}

export function GetConflict(arg1) {
  return window['go']['main']['App']['GetConflict'](arg1);
}

export function GetEntry(arg1) {
  return window['go']['main']['App']['GetEntry'](arg1);
}

export function GetServerURL() {
  return window['go']['main']['App']['GetServerURL']();
}

export function HasRegSecret() {
  return window['go']['main']['App']['HasRegSecret']();
}

export function ImportKeyfile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ImportKeyfile'](arg1, arg2, arg3, arg4);
}

export function IsAdminMode() {
  return window['go']['main']['App']['IsAdminMode']();
}

export function IsReinit() {
  return window['go']['main']['App']['IsReinit']();
}

export function IsUnlocked() {
  return window['go']['main']['App']['IsUnlocked']();
}

export function ListEntries() {
  return window['go']['main']['App']['ListEntries']();
}

export function Lock() {
  return window['go']['main']['App']['Lock']();
}

export function OpenFileDialog(arg1) {
  return window['go']['main']['App']['OpenFileDialog'](arg1);
}

export function PutEntry(arg1) {
  return window['go']['main']['App']['PutEntry'](arg1);
}

export function RegisterDevice(arg1, arg2) {
  return window['go']['main']['App']['RegisterDevice'](arg1, arg2);
}

export function ResolveConflict(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveConflict'](arg1, arg2, arg3);
}

export function Role() {
  return window['go']['main']['App']['Role']();
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}

export function SetCA(arg1) {
  return window['go']['main']['App']['SetCA'](arg1);
}

export function SetRegSecret(arg1) {
  return window['go']['main']['App']['SetRegSecret'](arg1);
}

export function SetServerURL(arg1) {
  return window['go']['main']['App']['SetServerURL'](arg1);
}

export function SetSyncMode(arg1) {
  return window['go']['main']['App']['SetSyncMode'](arg1);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function SyncMode() {
  return window['go']['main']['App']['SyncMode']();
}

export function SyncNow() {
  return window['go']['main']['App']['SyncNow']();
}

export function TryAutoUnlock() {
  return window['go']['main']['App']['TryAutoUnlock']();
}

export function Unlock(arg1, arg2) {
  return window['go']['main']['App']['Unlock'](arg1, arg2);
}

export function Username() {
  return window['go']['main']['App']['Username']();
}

export function VerifyServer(arg1, arg2) {
  return window['go']['main']['App']['VerifyServer'](arg1, arg2);
}
