// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {proto} from '../models';
import {api} from '../models';

export function AdminAddMember(arg1:string,arg2:string):Promise<void>;

export function AdminArchiveGroup(arg1:string,arg2:string):Promise<void>;

export function AdminCreateGroup(arg1:string):Promise<string>;

export function AdminCreateUser(arg1:string,arg2:string,arg3:string):Promise<string>;

export function AdminListDevices():Promise<Array<proto.AdminDevice>>;

export function AdminListGroups():Promise<Array<proto.GroupInfo>>;

export function AdminListMembers(arg1:string):Promise<Array<proto.GroupMemberInfo>>;

export function AdminListUsers():Promise<Array<proto.UserInfo>>;

export function AdminRemoveMember(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AdminUnarchiveGroup(arg1:string):Promise<void>;

export function AutoUnlockEnabled():Promise<boolean>;

export function Bootstrap(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function DataDir():Promise<string>;

export function DeleteEntry(arg1:string):Promise<void>;

export function DisableAutoUnlock():Promise<void>;

export function EnableAutoUnlock():Promise<void>;

export function ExportKeyfile(arg1:string):Promise<void>;

export function GenerateKeypair(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GeneratePassword(arg1:number,arg2:boolean,arg3:boolean,arg4:boolean,arg5:boolean,arg6:boolean):Promise<string>;

export function GetCA():Promise<string>;

export function GetConflict(arg1:string):Promise<api.ConflictDetail>;

export function GetEntry(arg1:string):Promise<api.EntryView>;

export function GetServerURL():Promise<string>;

export function HasRegSecret():Promise<boolean>;

export function ImportKeyfile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<api.UnlockResult>;

export function IsAdminMode():Promise<boolean>;

export function IsReinit():Promise<boolean>;

export function IsUnlocked():Promise<boolean>;

export function ListEntries():Promise<Array<api.EntryView>>;

export function Lock():Promise<void>;

export function OpenFileDialog(arg1:string):Promise<string>;

export function PutEntry(arg1:api.PutEntryRequest):Promise<void>;

export function RegisterDevice(arg1:string,arg2:string):Promise<void>;

export function ResolveConflict(arg1:string,arg2:boolean,arg3:Array<number>):Promise<void>;

export function Role():Promise<string>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function SetCA(arg1:string):Promise<void>;

export function SetRegSecret(arg1:string):Promise<void>;

export function SetServerURL(arg1:string):Promise<void>;

export function SetSyncMode(arg1:string):Promise<void>;

export function Status():Promise<api.SyncStatus>;

export function SyncMode():Promise<string>;

export function SyncNow():Promise<void>;

export function TryAutoUnlock():Promise<api.UnlockResult>;

export function Unlock(arg1:string,arg2:string):Promise<api.UnlockResult>;

export function Username():Promise<string>;

export function VerifyServer(arg1:string,arg2:string):Promise<void>;
